language: cpp

compiler:
  - gcc

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
    - secure: "Y2AIphxa/9WbmVGPpRD+MoxboIICxmOwXAA/oPk9xHbjcT8I9koFXP9jdPqRhR0sKjrR2T3CPfujsUbtXv3BjVj2vu8hgGIldfHUtFCr34iYXStmPtcklSkudboOMWMyKIUzUuKFG4XY1SOyNpll/n9GzSueGGBFh0sPTKrSLbE="
   
addons:
    coverity_scan:
      project:
        name: "HeadhunterXamd/cppAssignments"
        description: "Build submitted via Travis CI"
      notification_email: nielsvanschooten@gmail.com
      build_command_prepend: "mkdir build && cd build && cmake -G \"Unix Makefiles\" ~/HeadhunterXamd/cppAssignments/TafelOefening"
      build_command: "make -j4"
      branch_pattern: coverity_scan

script: if [ "${COVERITY_SCAN_BRANCH}" != 1 ]; then mkdir build && cd build && cmake -G "Unix Makefiles" ../TafelOefening/ && make -j4 ; fi
before_deploy:
    "travis setup releases"
deploy:
  provider: releases
  api-key: "GITHUB OAUTH TOKEN"
  file:
    - "TafelOefening.*"
  skip_cleanup: true
  on:
    tags: false
