objects = main.o question.o session.o table.o


edit : $(objects)
       cc -o edit $(objects)
       
main.o : main.cpp session.h
         
question.o : question.cpp question.h

session.o : session.cpp session.h

table.o : table.cpp table.h
